stages:
  - build
  - check

##Production(master-docker-compose)
building:
    stage: build
    script:
        - docker-compose -f .docker/docker-compose.yml up -d --build --force-recreate hd-wallet-address
    tags:
        - run_trader
    only:
        refs:
            - develop
checking:
    stage: check
    script:
        - docker-compose -f .docker/docker-compose.yml logs hd-wallet-address
        - docker-compose -f .docker/docker-compose.yml ps --services --filter "status=running" | grep "hd-wallet-address"
    tags:
        - check_trader
    only:
        refs:
            - develop
